# WhatATheme
markdown: kramdown

domain: tieraugen.doctor       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://Tieraugen.doctor  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl:       # place folder name if the site is served in a subfolder


# Title of the Site
title: Augentierarzt Greifswald
# Description of the Site
description: <br/>Augenerkrankungen sind bei unseren Haustieren sehr häufig. Eine spezialisierte Diagnostik und zielgerichtete Therapie sind entscheidend.

 <br/><br/>Auf dieser Webseite finden Sie interessante Informationen über gängige Augenerkrankungen von Hunden, Katzen und Heimtieren in der Wissensbank.

meta-description: Spezialisierte augentierärztliche Behandlung bei Ihrem Tier.

# URL of Image of the Site
site-image: https://tieraugen.doctor/assets/images/hero.jpg
# Keywords of the Site
site-keywords: Greifswald, Tieraugenarzt, Augentierarzt, Augen, Tieraugen, Ophthalmologie, Dortmunder Kreis, Augenheilkunde, Tierarzt, Sahr, Augenerkrankungen
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://tieraugen.doctor/assets/images/greifswald.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: tierauge@gmail.com

phone: +49 3834 504672

fax:  +49 3834 504673

mobile: +49 172 3006894

# Name of the Author
author-name: Dr. Sabine Sahr
# URL for the Image of the Author
author-image: ../assets/images/spaltlampe.jpg
# 60 Words About the Author
author-about: Ich bin Tierärztin mit Zusatzbezeichnung Augenheilkunde und Mitglied
 im <a target="blank_" href="https://www.dok-vet.de">Dortmunder Kreis (DOK)</a> - Gesellschaft für
 Diagnostik genetisch bedingter Augenerkrankungen. 
 
 Nach 4 Jahren an der Kleintierklinik der Universität Leipzig, arbeitete ich 6 Jahre
 in der Augen-Tierarztpraxis Dr. I. Allgoewer in Berlin. Anschließend übernahm 
 ich die Augenheilkunde in der Anicura Tierklinik Potsdam für 2 Jahre, bin jetzt in
 die Heimat zurückgekehrt und Teil des Teams der <a target="blank_" href="https://www.tieraerzte-quandtundbracke.de/quandtundbracke">Tierarztpraxis Quandt und Bracke</a>. 
 

twitter_username: TieraugenDoc
facebook_username: TieraugenDoc

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
#author-url: https://github.com/tierauge

# Adds id for google analytics
google-analytics: G-HB6RDYDEHG

open-mon:
open-tue:
open-wed: 12:30 - 14:30
open-thr:
open-fri: 12:30 - 14:30
open-sat:
open-sun:

linked-data: > 
    {
      "@context": "https://schema.org",
      "@type": "VeterinaryCare",
      "name": "Augentierarzt Greifswald",
      "medicalSpecialty": "Ophthalmology",
      "description": "Tierarzt Augen, Augenspezialist, Tieraugenheilkunde, Augen Tierarzt, Veterinärophthalmologie, Augentierarzt, Tieraugenarzt, Mecklenburg-Vorpommern, MV, Mecklenburg Vorpommern, Zuchtuntersuchung, DOK-Untersuchung, Dortmunder Kreis, Augenuntersuchung und Augenoperation bei Tieren",
      "slogan": "Tieraugenheilkunde",
      "telephone": "+493834504672",
      "email": "tierauge@gmail.com",
      "sameAs": [
        "https://www.facebook.com/tieraugendoc",
        "https://twitter.com/Tieraugendoc",
        "https://www.fvo-vet.de/foerderpreis.htm"
      ],
      "openingHours":[
        "Mi 12:30-14:30",
        "Fr 12:30-14:30"
      ],
      "member": [
      {
        "@type": "parentOrganization",
        "name": "Tierarztpraxis Quandt und Bracke",
        "url": "https://www.tieraerzte-quandtundbracke.de",
        "address": {
          "@type": "PostalAddress",
          "addressLocality": "Greifswald",
          "addressRegion": "MV",
          "postalCode": "17489",
          "streetAddress": "An den Wurthen 26",
          "geo": {
            "@type": "GeoCoordinates",
            "latitude": "54.097170",
            "longitude": "13.397257"
          }
        }
      },
      {
        "@type": "parentOrganization",
        "name": "Tierarztpraxis für Kleintiere Dipl.-Vet.-Med. Andrea Lehmann",
        "url": "https://lehmann-tierarzt.de",
        "address": {
          "@type": "PostalAddress",
          "addressLocality": "Neubrandenburg",
          "addressRegion": "MV",
          "postalCode": "17033",
          "streetAddress": "Fritz-Reuter-Straße 7",
          "geo": {
            "@type": "GeoCoordinates",
            "latitude": "53.560294345675",
            "longitude": "13.2548445529906"
          }
        }
      }
      ],
      "image": "https://tieraugen.doctor/assets/images/greifswald.jpg"
    }



excerpt_separator: "<!--excerpt-->"

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-figure

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
