# WhatATheme
markdown: kramdown

domain: tieraugen.doctor       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://Tieraugen.doctor  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl:       # place folder name if the site is served in a subfolder


# Title of the Site
title: Augentierarzt Greifswald
# Description of the Site
description: <br/>Augenerkrankungen sind bei unseren Haustieren sehr häufig. Eine spezialisierte Diagnostik und zielgerichtete Therapie sind entscheidend.

 <br/><br/>Auf dieser Webseite finden Sie interessante Informationen über gängige Augenerkrankungen von Hunden, Katzen und Heimtieren in der Wissensbank.

meta-description: Spezialisierte augentierärztliche Behandlung bei Ihrem Tier.

# URL of Image of the Site
site-image: https://tieraugen.doctor/assets/images/hero.jpg
# Keywords of the Site
site-keywords: Greifswald, Tieraugenarzt, Augentierarzt, Augen, Tieraugen, Ophthalmologie, Dortmunder Kreis, Augenheilkunde
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://tieraugen.doctor/assets/images/greifswald.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: tierauge@gmail.com

phone: +49 3834 504672

fax:  +49 3834 504673

mobile: +49 172 3006894

# Name of the Author
author-name: Dr. Sabine Sahr
# URL for the Image of the Author
author-image: ../assets/images/Spaltlampe.jpg
# 60 Words About the Author
author-about: Ich bin Tierärztin mit Zusatzbezeichnung Augenheilkunde und Mitglied
 im <a target="blank_" href="https://www.dok-vet.de">Dortmunder Kreis (DOK)</a> - Gesellschaft für
 Diagnostik genetisch bedingter Augenerkrankungen. 
 
 Nach 4 Jahren an der Kleintierklinik der Universität Leipzig, arbeitete ich 6 Jahre
 in der Augen-Tierarztpraxis Dr. I. Allgoewer in Berlin. Anschließend übernahm 
 ich die Augenheilkunde in der Anicura Tierklinik Potsdam für 2 Jahre, bin jetzt in
 die Heimat zurückgekehrt und Teil des Teams der <a target="blank_" href="https://www.tieraerzte-quandtundbracke.de/quandtundbracke">Tierarztpraxis Quandt und Bracke</a>. 
 

twitter_username: Tieraugendoc
facebook_username: Tieraugen.doctor

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
#author-url: https://github.com/tierauge

# Adds id for google analytics
google-analytics: G-HB6RDYDEHG

open-mon: 12 - 17 Uhr
open-tue: 9 - 14 Uhr
open-wed: 9 - 14 Uhr
open-thr:
open-fri: 13 - 18 Uhr
open-sat:
open-sun:


excerpt_separator: "<!--excerpt-->"

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-figure

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
